//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi_mvc_crud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class newempreg
    {
        public int empid { get; set; }
        public string empname { get; set; }
        public string empmail { get; set; }
        public string emplocation { get; set; }
        public string empdesignation { get; set; }
    }
}
